AS=as
GCC=gcc

GRUB_LIB=/usr/lib/grub/x86_64-pc

all: testos.iso

clean:
	rm -f *.ali *.o b-*.adb b-*.ads kernel.bin testos.iso
	rm -rf isodir

boot.o: boot.s
	$(AS) boot.s -o boot.o

b-kernel_init.adb b-kernel_init.ads: kernel_init.ali terminal.ali
	gnatbind kernel_init.ali

terminal.ali: terminal.adb
	$(GCC) -c terminal.adb

kernel_init.ali: kernel_init.adb 
	$(GCC) -c kernel_init.adb

kernel.bin: boot.o kernel_init.ali b-kernel_init.adb b-kernel_init.ads link.sh
	gnatlink kernel_init.ali boot.o --LINK=./link.sh -o kernel.bin

testos.iso: grub/* kernel.bin
	mkdir -p isodir/boot/grub
	cp $(GRUB_LIB)/stage2_eltorito isodir/boot/grub
	cp grub/* isodir/boot/grub
	cp kernel.bin isodir/boot/kernel.bin
	genisoimage -R -b boot/grub/stage2_eltorito \
		-no-emul-boot -boot-load-size 4 -boot-info-table \
		-o testos.iso isodir
