/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2016-3-16: 18h:54m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.2.6/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_stafun(output_char_at, (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_char)), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
/home/nathan/bare-bones-kernel-collection/ats2/kernel.dats: 130(line=5, offs=1) -- 787(line=25, offs=3)
*/
ATSextcode_beg()
  #include <stddef.h>
  #include <stdint.h>

  #define VIDEO_MEMORY_ADDRESS 0x000B8000

  #define VGA_WIDTH  80
  #define VGA_HEIGHT 25

  // Prints character with green text.
  // VGA memory is represented as an array of 2 byte records.
  // First byte is the color (left nibble for bg, right for fg).
  // Second byte is the character.
  static void output_char_at(int x, int y, char character) {
    // 0x02 == (0 for black bg, 2 for green fg)
    uint16_t cell = 0x0200 | (uint16_t)character;
    int index = (y * VGA_WIDTH) + x;
    ptrdiff_t offset = index * sizeof(uint16_t);
    *(volatile uint16_t*)(VIDEO_MEMORY_ADDRESS + offset) = cell;
  }
ATSextcode_end()
#if(0)
ATSextern()
atsvoid_t0ype
kernel_main() ;
#endif // end of [QUALIFIED]

/*
/home/nathan/bare-bones-kernel-collection/ats2/kernel.dats: 861(line=28, offs=22) -- 891(line=28, offs=52)
*/
/*
local: 
global: kernel_main$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
kernel_main()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/nathan/bare-bones-kernel-collection/ats2/kernel.dats: 850(line=28, offs=11) -- 891(line=28, offs=52)
*/
ATSINSflab(__patsflab_kernel_main):
/*
emit_instr: loc0 = /home/nathan/bare-bones-kernel-collection/ats2/kernel.dats: 866(line=28, offs=27) -- 891(line=28, offs=52)
*/
ATSINSmove_void(tmpret0, output_char_at(ATSPMVi0nt(0), ATSPMVi0nt(0), ATSPMVchar('@'))) ;

ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [kernel_main] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_nathan_057_bare_055_bones_055_kernel_055_collection_057_ats2_057_kernel_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_nathan_057_bare_055_bones_055_kernel_055_collection_057_ats2_057_kernel_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_nathan_057_bare_055_bones_055_kernel_055_collection_057_ats2_057_kernel_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_nathan_057_bare_055_bones_055_kernel_055_collection_057_ats2_057_kernel_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_nathan_057_bare_055_bones_055_kernel_055_collection_057_ats2_057_kernel_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
/*
/home/nathan/bare-bones-kernel-collection/ats2/kernel.dats: 893(line=30, offs=1) -- 940(line=34, offs=3)
*/
ATSextcode_beg()
void kernel_entry() {
  kernel_main();
}
ATSextcode_end()

/* ****** ****** */

/* end-of-compilation-unit */
